server:
  port: 8043
  context-path: /auth

security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/share_cash
    username: share_cash
    password: share_cash_123
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
  data:
    rest:
      base-path: /jpa