server:
  port: 8090
  session:
    cookie:
      name: JSESSIONID
      max-age: -1

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/share_cash
    username: share_cash
    password: share_cash_123
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
  data:
    rest:
      base-path: /jpa

logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate: WARN
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"