spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/static/templates/
  resources:
    static-locations: file:src/main/resources/static/

server:
  port: 8070
  session:
    timeout: 86400
    cookie:
      name: JSESSIONID
      max-age: -1

engine:
  url: @engine.url@

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ShareCashApp
      clientSecret: f7f5d77e76a67f787ef6da8c
      accessTokenUri: http://localhost:8043/auth/oauth/token
      userAuthorizationUri: http://localhost:8043/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8043/auth/user/me