spring:
  thymeleaf:
    cache: false
    prefix: @thymleaf.templates.path@
  resources:
    static-locations: @thymleaf.static.path@

server:
  port: 80
  session:
    timeout: 86400
    cookie:
      name: JSESSIONID
      max-age: -1

engine:
  url: @engine.url@

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ShareCashApp
      clientSecret: f7f5d77e76a67f787ef6da8c
      accessTokenUri: @sso.uri.access.token@
      userAuthorizationUri: @sso.uri.user.authorization@
    resource:
      userInfoUri: @sso.uri.user.info@